### PR TITLE
background is a black to red linear gradient

### LINKED ISSUE #2: Phase 1: Website Body
# Body

home page

> This is a prototype of the homepage that includes the header, background, and footer.

The body of the page should be a black to red fade using the official colors of the University of Louisville.

## Requirements Checklist:

- [x] Body should include the title of the page currently selected

- [x] Background should be a black to red fade

CardTech website background

- [x] 50% black

- [x]  Blur between colors in the middle ( 15%)

- [x] 50% red

- [x] background will cover the entire page

- [x] Body should be part of an ASP.NET template, allowing other pages to insert their `<body>` content into the template.

### PR DESCRIPTION
**Pull request by Erika-Maglasang**
background for the body of the homepage

### CODE REVIEW

**Review by JCDILL03 — COMMENTED** [review]
Looks good to me

**Comment by brandonberney** [comment]
Before we merge this in, I would like to see this in a designed CSS file. I'll work on moving it into the right place when we have a chance.

**Review by diagnose — CHANGES_REQUESTED** [review]
Before we merge this in, I would like to see this in a designed CSS file. I'll work on moving it into the right place when we have a chance.

**Comment by diagnose** [comment]
Closing this since we also have #24.

**Pull request closed without merging**
