### PR TITLE
Login/Register Pop-up

### LINKED ISSUE #10: Phase 1: Login
CardTech Inc sample page

- [ ] A click link is located on the home bar titled **log In**

CardTech Inc Login frame

- [ ] This window will popup in center of the page after the user clicks on it.

- [ ] the window has rounded edges

- [ ] The user will be able to input their username and password to login to their profile

- [ ] The database will be cross references to ensure that this is a valid username and password

- [ ] An error message will be outputted if this is not a valid user

- [ ] The user will be able to login with their Ulink ID

- [ ] The user will be able to register or create an account from the window

- [ ] They will be sent to a create account form

### PR DESCRIPTION
**Pull request by doncun163**
I've add the style css in the head. Added the html codes for the Login/Register Modal. Changed the navbar-links to open the modal whenever clicked. The Login/Register modal should pop up whenever you click on it. If you want already have an account, clicking "Login" at the bottom will bring you to the login modal.

### CODE REVIEW

**Review by diagnose — CHANGES_REQUESTED** [review]
Hey Don, something is messed up here. Your commit was only a change to the launchSettings.json file, which shouldn't be touched anyways. Let me know when you're free and I can help walk you through this.

Side note: We also need to update the email you're committing as to make sure you get credit for the code you write ☺️

**Review by Erika-Maglasang — COMMENTED** [review]
I added an additional step the the Guide for making Pull requests. After you make your commits go to the synchronization in the team explored. Look under Ongoing Commits and click "Push".
This will update the changes that you made to the branch and make your code visible to other team members. This Pull request will also be updated automatically after Synchronization.

**Review by Erika-Maglasang — APPROVED** [review]
looks good, and works fine

**Review by JCDILL03 — APPROVED** [review]
The code looks good to me

**Review by Erika-Maglasang — APPROVED** [review]
resolved the conflict should be good to merge

**Review by Erika-Maglasang — APPROVED** [review]
Conflict has been resolved by merging the branch with Phase one color. This branch is up to date.

**Comment by diagnose** [comment]
Closing since we've implemented #35.

**Pull request closed without merging**
