### PR TITLE
enhancement: create issue templates

### LINKED ISSUE #22: Enhancement: Issue/PR Templates
It is possible to create templates for issues and pull requests.

See the article [here.](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates)

Although we already have many issues created, it may still be helpful to create templates for these and especially pull requests.

Thoughts?

### PR DESCRIPTION
**Pull request by diagnose**
This resolves #22.

Templates are added for issues and pull requests, which will help provide a uniform reporting method for issues and pull requests.

### CODE REVIEW

**Review by Erika-Maglasang — APPROVED** [review]
Looks good. Where will this be located after the pull request has been approved?

**Comment by diagnose** [comment]
> Looks good. Where will this be located after the pull request has been approved?

The files itself are in an invisible `.github` folder in the root directory, which you can see in the branch.

However, you should be given a prompt to select a template when trying to create a new issue or pull request.

**Review by doncun163 — APPROVED** [review]
Nice, seems like a good idea to me

**Comment by diagnose** [comment]
Merging.

**Pull request merged**
