### PR TITLE
Phase 1: Footer

### LINKED ISSUE #3: Phase 1: Website Footer
# Footer

Footer

> This is a prototype of the footer.

For the first phase of this project, links provided in the header should point to other pages.

## Requirements Checklist:

The footer shall have 5 columns:

### Column 1: Logo

~Includes the University of Louisville logo~

#### When not signed in...

- [x] Includes a link to log in

- [x] Includes a link to register

#### When signed in...

* Reserved for future implementation

### Column 3: Contact Us

- [x] Includes a telephone number to the department

- [x] Includes a fax number to the department

- [x] Includes a social media link to Twitter

- [x] Includes a social media link to Facebook

- [x] Includes a social media link to LinkedIn

### Column 4: Resources

- [x] Includes a resources link for students

- [x] Includes a resources link for industry members

- [x] Includes a resources link for community members

- [x] Includes a resources link for researchers

### Column 5: Copyright

- [x] Includes text that says "Powered by CardTech"

### PR DESCRIPTION
**Pull request by diagnose**
This pull request resolves #3.

I have decided to leave out color customization and the University of Louisville logo.

* Color customization can be implemented at any time.
* We currently do not have the permission to actually use the logo. We should reach out to someone to make sure we have permission and can get a properly sized logo.

**This PR also fixes an issue with header links not working.**

# Desktop Example:
Desktop screenshot

# Mobile Example:
Mobile screenshot

# Tablet Example:
Tablet screenshot, landscape

# Table Example 2:
Tablet screenshot, portrait

### CODE REVIEW

**Review by Erika-Maglasang — APPROVED** [review]
This looks good, It seems that the flex command has solved all our formatting problems for the header and the footer. Does it also work with the background? I'm gonna play around with it a separate CSS file.

**Comment by diagnose** [comment]
> This looks good, It seems that the flex command has solved all our formatting problems for the header and the footer. Does it also work with the background? I'm gonna play around with it a separate CSS file.

Yes, because the flex styling makes the footer stick to the bottom of the page, it should help with the issue you were having with the background fade not taking over the whole screen.

**Review by doncun163 — APPROVED** [review]
Looks good

**Review by GMStull — APPROVED** [review]
Looks great to me, I can see a bit more from this how to utilize bootstrap properly.

**Comment by diagnose** [comment]
Received minimum approvals. Merged.

**Pull request merged**
